Repository BLAST-ImpactX/impactx, pull requests merged in 2021-12, with the labels that each got.

#20 CMAKE_INSTALL_LIBDIR: Absolute (or auto-prefixed)
  CMakeLists.txt
Labels: bug

#22 Fix: Installed Symlink LIB
  CMakeLists.txt
Labels: bug

#23 Fix: Elements `operator()` is `const`
  src/particles/elements/Drift.H
  src/particles/elements/Quad.H
  src/particles/elements/Sbend.H
Labels: bug

#21 Added declaration and initialization of a list of beamline elements.
  src/ImpactX.H
  src/ImpactX.cpp
  src/main.cpp
  src/particles/Push.H
  src/particles/Push.cpp
  src/particles/elements/All.H
Labels: enhancement

#25 AMReX: 21.12
  cmake/dependencies/AMReX.cmake
Labels: enhancement

#28 Superbuild: C++17 in AMReX/PICSAR/openPMD-api
  CMakeLists.txt
  cmake/ImpactXFunctions.cmake
Labels: install

#27 Doxygen: `PushSingleParticle::operator()`
  src/particles/Push.cpp
Labels: component: documentation

#19 Resize grid based on beam extent
  src/ImpactX.H
  src/ImpactX.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
Labels: enhancement

#31 Limit the scope of profiler
  src/main.cpp
Labels: backend: dpc++

#29 Use ABLASTR: WarpX Routines
  CMakeLists.txt
  cmake/ImpactXFunctions.cmake
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/openPMD.cmake
  docs/source/install/cmake.rst
Labels: install

#26 Add first input script
  .github/workflows/ubuntu.yml
  docs/source/usage/parameters.rst
  examples/input_fodo.in
  src/ImpactX.cpp
Labels: changes input scripts / defaults

#34 Added parsing of basic beam parameters from input file.
  examples/input_fodo.in
  src/ImpactX.H
  src/ImpactX.cpp
Labels: changes input scripts / defaults, component: core

#38 Doxygen: include `static` functions
  docs/Doxyfile
Labels: component: documentation

#37 README: Document Inputs File Usage
  README.md
Labels: component: documentation
