Repository BLAST-ImpactX/impactx, pull requests merged in 2022-04, with the labels that each got.

#105 Added new distribution types: 6D Gaussian & 4D K-V
  docs/source/usage/parameters.rst
  src/ImpactX.cpp
  src/particles/distribution/Gaussian.H
  src/particles/distribution/KVdist.H
Labels: component: core

#106 Fix: CMake AMReX Repo
  cmake/dependencies/ABLASTR.cmake
Labels: bug, install, component: third party

#107 Initialization: Split Files
  src/CMakeLists.txt
  src/ImpactX.H
  src/ImpactX.cpp
  src/initialization/CMakeLists.txt
  src/initialization/InitDistribution.cpp
  src/initialization/InitElement.cpp
  src/initialization/InitMeshRefinement.cpp
  src/initialization/InitParser.H
  src/initialization/InitParser.cpp
  src/main.cpp
  src/particles/diagnostics/DiagnosticOutput.H
  src/particles/diagnostics/DiagnosticOutput.cpp
Labels: component: core, component: elements

#108 Deduplicate Distribution Init
  src/initialization/InitDistribution.cpp
Labels: component: core

#73 Parallelize particle initialization
  cmake/dependencies/ABLASTR.cmake
  src/initialization/InitDistribution.cpp
  src/particles/ImpactXParticleContainer.cpp
Labels: component: core

#109 IO: Parallel Particle ASCII Output
  examples/CMakeLists.txt
  examples/cfchannel/analysis_cfchannel.py
  examples/chicane/analysis_chicane.py
  examples/fodo/analysis_fodo.py
  examples/kurth/analysis_kurth.py
  src/particles/diagnostics/DiagnosticOutput.H
  src/particles/diagnostics/DiagnosticOutput.cpp
Labels: component: core

#111 Added benchmark examples to test Gaussian and KV distributions.
  examples/CMakeLists.txt
  examples/distgen/analysis_gaussian.py
  examples/distgen/analysis_kvdist.py
  examples/distgen/input_gaussian.in
  examples/distgen/input_kvdist.in
Labels: component: tests

#112 Added a short RF (bunching) cavity element based on MaryLie.
  docs/source/usage/parameters.rst
  examples/CMakeLists.txt
  examples/fodo_rf/README.rst
  examples/fodo_rf/analysis_fodo_rf.py
  examples/fodo_rf/input_fodo_rf.in
  src/initialization/InitElement.cpp
  src/particles/elements/All.H
  src/particles/elements/ShortRF.H
Labels: component: core

#115 Added a Semi-Gaussian distribution and example.
  docs/source/usage/parameters.rst
  examples/CMakeLists.txt
  examples/distgen/analysis_semigaussian.py
  examples/distgen/input_semigaussian.in
  src/initialization/InitDistribution.cpp
  src/particles/distribution/Semigaussian.H
Labels: component: core

#119 CI: Update CUDA repo key
  .github/workflows/dependencies/nvcc11.sh
Labels: backend: cuda, component: tests

#117 Modify documentation of quad and short RF cavity.
  docs/source/usage/parameters.rst
Labels: component: documentation
