Repository BLAST-ImpactX/impactx, pull requests merged in 2022-12, with the labels that each got.

#280 Add CodeQL Scanning
  .github/workflows/codeql.yml
Labels: component: tests

#279 Added refinements to the expanding beam benchmark.
  examples/expanding_beam/input_expanding.in
  examples/expanding_beam/run_expanding.py
Labels: component: tests

#281 Python Examples: Unused Imports
  examples/chicane/plot_chicane.py
  examples/fodo/plot_fodo.py
Labels: component: tests, component: python

#282 Push: Move RefParticle in Constructor
  src/particles/Push.cpp
Labels: Performance optimization

#286 Elements: RefParticle ByRef
  src/particles/elements/ConstF.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/Multipole.H
  src/particles/elements/None.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/Quad.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
Labels: component: elements, Performance optimization

#222 Add struct and input for RF cavity element
  docs/source/usage/examples.rst
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  examples/rfcavity/README.rst
  examples/rfcavity/analysis_rfcavity.py
  examples/rfcavity/input_rfcavity.in
  examples/rfcavity/run_rfcavity.py
  src/ImpactX.cpp
  src/initialization/InitElement.cpp
  src/particles/CMakeLists.txt
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/particles/Push.cpp
  src/particles/ReferenceParticle.H
  src/particles/elements/All.H
  src/particles/elements/RFCavity.H
  src/particles/integrators/Integrators.H
  src/python/elements.cpp
Labels: component: elements

#288 Release: 22.12
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation, component: third party
