Repository BLAST-ImpactX/impactx, pull requests merged in 2022-03, with the labels that each got.

#58 Charge over mass
  src/ImpactX.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
Labels: component: core

#72 Changes to allow benchmark of matched zero-current FODO lattice.
  examples/input_fodo.in
  src/main.cpp
  src/particles/elements/Quad.H
Labels: bug, component: core, component: elements

#74 CI: ccache
  .github/workflows/cuda.yml
  .github/workflows/dependencies/gcc.sh
  .github/workflows/dependencies/hip.sh
  .github/workflows/dependencies/nvcc11.sh
  .github/workflows/hip.yml
  .github/workflows/ubuntu.yml
Labels: backend: cuda, backend: hip, backend: openmp

#75 Made changes needed to include a chicane benchmark.
  docs/source/usage/parameters.rst
  examples/input_chicane.in
  src/ImpactX.cpp
  src/particles/elements/All.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/Quad.H
  src/particles/elements/Sbend.H
Labels: component: elements

#78 add Axel's comments
  src/ImpactX.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
Labels: component: documentation

#77 Docs: Fix Parameters (Close Verbatim)
  docs/source/usage/parameters.rst
Labels: component: documentation

#80 Doc: Update for Testing on NERSC
  README.md
  docs/source/install/hpc/cori.rst
  docs/source/install/hpc/perlmutter.rst
Labels: component: documentation, machine / system, install

#82 Version Define File
  CMakeLists.txt
  src/ImpactXVersion.H.in
Labels: bug, install

#84 Theory: Start Assumptions
  docs/source/theory/intro.rst
Labels: component: documentation

#79 Update: ABLASTR
  CMakeLists.txt
  cmake/ImpactXFunctions.cmake
  cmake/dependencies/ABLASTR.cmake
  src/particles/ImpactXParticleContainer.cpp
Labels: component: third party

#87 Doc: Major Cori Update
  README.md
  docs/source/install/hpc/cori.rst
Labels: component: documentation, machine / system, install

#86 Tests: Run Chicane Analysis
  CMakeLists.txt
  docs/source/install/cmake.rst
  examples/CMakeLists.txt
Labels: component: tests

#85 Added a linear constant focusing element.
  docs/source/usage/parameters.rst
  examples/CMakeLists.txt
  examples/cfchannel/README.rst
  examples/cfchannel/analysis_cfchannel.py
  examples/cfchannel/input_cfchannel.in
  src/ImpactX.cpp
  src/particles/elements/All.H
  src/particles/elements/ConstF.H
Labels: component: elements

#89 Docs: Link Constant Focusing Channel
  docs/source/usage/examples.rst
Labels: component: documentation

#92 Modified cfchannel element to contain corrected factors of beta*gamma
  examples/cfchannel/input_cfchannel.in
  examples/kurth/input_kurth.in
  src/particles/elements/ConstF.H
Labels: component: elements

#88 Docs: Update Assumptions
  docs/source/theory/intro.rst
Labels: component: documentation

#91 Fix MR Level Loops: `finestLevel()`
  src/particles/ChargeDeposition.cpp
  src/particles/Push.cpp
  src/particles/diagnostics/DiagnosticOutput.cpp
  src/particles/transformation/CoordinateTransformation.cpp
Labels: bug, bug: affects latest release
