Repository BLAST-ImpactX/impactx, pull requests merged in 2022-08, with the labels that each got.

#188 ABLASTR: 22.08
  cmake/dependencies/ABLASTR.cmake
Labels: component: third party

#189 Add `algo.space_charge`
  docs/source/usage/parameters.rst
  examples/fodo/run_fodo.py
  examples/iota_lattice/run_iotalattice.py
  src/ImpactX.cpp
  src/python/ImpactX.cpp
Labels: changes input scripts / defaults, component: space charge

#191 Diagnostics: Benchmark Control
  docs/source/usage/parameters.rst
  examples/fodo/run_fodo.py
  examples/iota_lattice/run_iotalattice.py
  src/ImpactX.cpp
  src/python/ImpactX.cpp
  tests/python/test_impactx.py
Labels: changes input scripts / defaults, component: diagnostics

#193 ImpactX: 22.08
  CMakeLists.txt
  docs/source/conf.py
  setup.py
Labels: component: documentation

#194 Doc: Development Status Alpha
  README.md
  docs/source/index.rst
  setup.py
Labels: component: documentation

#196 Add Zenodo Metadata
  .zenodo.json
Labels: component: documentation

#197 README: Add Source Archive
  README.md
Labels: component: documentation

#201 Docs: Fix FODO-RF Label
  examples/fodo_rf/README.rst
Labels: bug, component: documentation, bug: affects latest release

#200 Docs: Python API in the Manual
  docs/source/index.rst
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  src/ImpactX.H
  src/particles/ImpactXParticleContainer.H
  src/particles/elements/NonlinearLens.H
  src/python/ImpactX.cpp
  src/python/ImpactXParticleContainer.cpp
  src/python/ReferenceParticle.cpp
  src/python/distribution.cpp
  src/python/elements.cpp
Labels: component: documentation, component: python

#165 Test: Charge Deposition
  cmake/dependencies/ABLASTR.cmake
  examples/fodo/input_fodo.in
  examples/fodo/run_fodo.py
  src/ImpactX.H
  src/initialization/InitDistribution.cpp
  src/particles/ChargeDeposition.cpp
  src/particles/ImpactXParticleContainer.cpp
  src/python/ImpactX.cpp
  tests/python/test_charge_deposition.py
Labels: bug, bug: affects latest release, component: space charge, component: tests

#204 `isort`: AMReX and ImpactX as First Party
  .editorconfig
  tests/python/conftest.py
  tests/python/test_charge_deposition.py
Labels: component: tests, component: python

#206 Docs: Add NAPAC'22 Paper
  README.md
  docs/source/acknowledge_us.rst
Labels: component: documentation

#207 Add Python Script to Chicane example
  examples/CMakeLists.txt
  examples/chicane/README.rst
  examples/chicane/run_chicane.py
Labels: component: tests, component: python

#205 CI: Windows
  .github/workflows/windows.yml
  CMakeLists.txt
  MANIFEST.in
  README.md
  cmake/dependencies/ABLASTR.cmake
  docs/source/developers/testing.rst
  docs/source/install/cmake.rst
  docs/source/install/dependencies.rst
  examples/CMakeLists.txt
  setup.py
Labels: bug, bug: affects latest release, install, component: tests, component: python

#209 CMake: Simplify Example Tests
  .github/workflows/ubuntu.yml
  examples/CMakeLists.txt
Labels: install, component: tests

#212 Examples: 1nC, no Space Charge
  examples/cfchannel/input_cfchannel.in
  examples/chicane/input_chicane.in
  examples/chicane/run_chicane.py
  examples/distgen/input_gaussian.in
  examples/distgen/input_kurth4d.in
  examples/distgen/input_kvdist.in
  examples/distgen/input_semigaussian.in
  examples/fodo/input_fodo.in
  examples/fodo_rf/input_fodo_rf.in
  examples/iota_lattice/input_iotalattice.in
  examples/iota_lattice/run_iotalattice.py
  examples/iota_lens/input_iotalens.in
  examples/kurth/input_kurth.in
  examples/multipole/input_multipole.in
  tests/python/test_charge_deposition.py
Labels: component: tests

#211 Tests/Python: add multipole python test
  examples/CMakeLists.txt
  examples/multipole/README.rst
  examples/multipole/run_multipole.py
Labels: component: tests, component: python

#215 Python: 3.7+
  README.md
  setup.py
Labels: component: documentation, install, component: python

#213 add iota lens and kurth python examples
  examples/CMakeLists.txt
  examples/iota_lens/README.rst
  examples/iota_lens/run_iotalens.py
  examples/kurth/README.rst
  examples/kurth/run_kurth.py
Labels: component: tests, component: python

#221 Fix: Python List Iteration
  src/python/elements.cpp
Labels: bug, bug: affects latest release, component: python

#218 Examples: Tabs and Dropdowns
  docs/requirements.txt
  docs/source/conf.py
  docs/spack.yaml
  examples/cfchannel/README.rst
  examples/chicane/README.rst
  examples/fodo/README.rst
  examples/fodo_rf/README.rst
  examples/iota_lattice/README.rst
  examples/iota_lens/README.rst
  examples/kurth/README.rst
  examples/multipole/README.rst
Labels: component: documentation

#217 Pre-Commit: Python Formatting
  .pre-commit-config.yaml
  docs/source/conf.py
  examples/cfchannel/analysis_cfchannel.py
  examples/chicane/analysis_chicane.py
  examples/chicane/plot_chicane.py
  examples/chicane/run_chicane.py
  examples/distgen/analysis_gaussian.py
  examples/distgen/analysis_kurth4d.py
  examples/distgen/analysis_kvdist.py
  examples/distgen/analysis_semigaussian.py
  examples/fodo/analysis_fodo.py
  examples/fodo/plot_fodo.py
  examples/fodo/run_fodo.py
  examples/fodo_rf/analysis_fodo_rf.py
  examples/iota_lattice/analysis_iotalattice.py
  examples/iota_lattice/run_iotalattice.py
  examples/iota_lens/analysis_iotalens.py
  examples/iota_lens/run_iotalens.py
  examples/kurth/analysis_kurth.py
  examples/kurth/run_kurth.py
  examples/multipole/analysis_multipole.py
  examples/multipole/run_multipole.py
  setup.py
  tests/python/conftest.py
  tests/python/test_charge_deposition.py
  tests/python/test_impactx.py
Labels: component: tests, component: python

#220 Docs: Conda Package
  docs/source/install/users.rst
Labels: install

#225 Plot Scripts: Fix `--save-png` Call
  examples/CMakeLists.txt
Labels: bug, component: tests

#226 Fix: PYTHONPATH for CTest
  examples/CMakeLists.txt
Labels: bug, component: tests

#227 pytest Plot Scripts: Non-interactive
  cmake/ImpactXFunctions.cmake
  examples/CMakeLists.txt
  tests/python/CMakeLists.txt
  tests/python/test_charge_deposition.py
Labels: bug, component: tests

#229 Reference Particle: Store Charge & Mass
  docs/source/usage/python.rst
  examples/chicane/run_chicane.py
  examples/fodo/run_fodo.py
  examples/iota_lattice/run_iotalattice.py
  examples/iota_lens/run_iotalens.py
  examples/kurth/run_kurth.py
  examples/multipole/run_multipole.py
  src/ImpactX.H
  src/initialization/InitDistribution.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/python/ImpactX.cpp
  src/python/ReferenceParticle.cpp
  tests/python/test_impactx.py
Labels: enhancement, changes input scripts / defaults, component: python

#230 Reference Particle: GPU Capable Methods
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/particles/ReferenceParticle.H
  src/python/ReferenceParticle.cpp
Labels: backend: cuda, backend: dpc++, backend: hip, component: distributions
