Repository BLAST-ImpactX/impactx, pull requests merged in 2022-01, with the labels that each got.

#35 Max Level: From AMRinfo
  src/ImpactX.cpp
  src/particles/Push.cpp
Labels: component: core

#42 Doc: Draft full evolve loop
  src/ImpactX.H
  src/ImpactX.cpp
Labels: component: documentation

#46 Doc: Update Comments in PIC Loop
  src/ImpactX.cpp
Labels: component: documentation

#48 Fix order in which min/max is extracted from ABLASTR function
  src/ImpactX.cpp
Labels: bug

#47 Particle Init: 1->8
  src/ImpactX.cpp
Labels: workaround

#51 Docs: Clang 7+
  docs/source/install/dependencies.rst
Labels: component: documentation, install

#50 Sphinx: Clean Warnings/Formatting
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/source/developers/documentation.rst
  docs/source/install/cmake.rst
  docs/source/usage/parameters.rst
Labels: component: documentation

#39 Beam Init: Waterbag Distribution
  docs/source/usage/parameters.rst
  examples/input_fodo.in
  src/ImpactX.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/particles/distribution/Waterbag.H
Labels: component: core
