Repository BLAST-ImpactX/impactx, pull requests merged in 2022-07, with the labels that each got.

#157 Quad: Fix Abs Math Truncation
  src/particles/elements/Quad.H
Labels: bug, bug: affects latest release, component: elements

#155 Add More Profiling
  src/ImpactX.cpp
  src/initialization/InitDistribution.cpp
  src/initialization/InitElement.cpp
  src/particles/Push.cpp
Labels: component: core, component: elements, component: distributions

#159 Update ABLASTR
  cmake/dependencies/ABLASTR.cmake
Labels: component: third party

#160 Modified ordering of evolve/push loop.
  src/ImpactX.cpp
  src/particles/Push.H
  src/particles/Push.cpp
Labels: component: elements, component: space charge

#161 Density: MPI Comms
  src/particles/ChargeDeposition.cpp
  src/particles/ImpactXParticleContainer.H
Labels: component: space charge

#164 Update ABLASTR: Poisson API
  cmake/dependencies/ABLASTR.cmake
Labels: component: third party, component: space charge

#166 Python: Activate One Test
  tests/python/test_impactx.py
Labels: component: tests, component: python

#150 Added (optional) input per element - number of space charge slices.
  docs/source/usage/parameters.rst
  src/ImpactX.H
  src/ImpactX.cpp
  src/initialization/InitElement.cpp
  src/main.cpp
  src/particles/diagnostics/DiagnosticOutput.cpp
  src/particles/elements/ConstF.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/Multipole.H
  src/particles/elements/None.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/Quad.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
  src/python/ImpactX.cpp
  src/python/elements.cpp
  tests/python/test_impactx.py
Labels: component: elements, component: space charge

#168 Elements: slice `ds`
  src/particles/elements/ConstF.H
  src/particles/elements/Drift.H
  src/particles/elements/Quad.H
  src/particles/elements/Sbend.H
Labels: component: elements, component: space charge

#169 Diagnostics: Zero-Based
  examples/cfchannel/analysis_cfchannel.py
  examples/chicane/analysis_chicane.py
  examples/distgen/analysis_gaussian.py
  examples/distgen/analysis_kurth4d.py
  examples/distgen/analysis_kvdist.py
  examples/distgen/analysis_semigaussian.py
  examples/fodo/analysis_fodo.py
  examples/fodo_rf/analysis_fodo_rf.py
  examples/iota_lens/analysis_iotalens.py
  examples/kurth/analysis_kurth.py
  examples/multipole/analysis_multipole.py
  src/ImpactX.cpp
  src/particles/diagnostics/DiagnosticOutput.H
  src/particles/diagnostics/DiagnosticOutput.cpp
Labels: component: diagnostics

#167 Starting Plotting of Benchmarks
  examples/CMakeLists.txt
  examples/chicane/input_chicane.in
  examples/chicane/plot_chicane.py
  examples/fodo/input_fodo.in
  examples/fodo/plot_fodo.py
  examples/requirements.txt
Labels: component: tests

#171 Simplify diagnostic: NonLinear Invariants Only Initial/Final
  src/ImpactX.cpp
Labels: component: diagnostics

#153 Python: Init Beam Distributions
  examples/CMakeLists.txt
  examples/fodo/README.rst
  examples/fodo/run_fodo.py
  src/ImpactX.cpp
  src/initialization/CMakeLists.txt
  src/initialization/InitAMReX.H
  src/initialization/InitAMReX.cpp
  src/initialization/InitDistribution.H
  src/initialization/InitDistribution.cpp
  src/initialization/InitOneBoxPerRank.cpp
  src/main.cpp
  src/particles/diagnostics/DiagnosticOutput.cpp
  src/particles/distribution/All.H
  src/particles/distribution/None.H
  src/particles/transformation/CoordinateTransformation.H
  src/particles/transformation/CoordinateTransformation.cpp
  src/python/CMakeLists.txt
  src/python/ImpactX.cpp
  src/python/ImpactXParticleContainer.cpp
  src/python/ReferenceParticle.cpp
  src/python/distribution.cpp
  src/python/pyImpactX.cpp
  tests/python/CMakeLists.txt
  tests/python/test_impactx.py
Labels: component: python

#173 FODO/Chicane: Include Images in Docs
  docs/source/usage/examples.rst
  examples/chicane/README.rst
  examples/fodo/README.rst
Labels: component: documentation

#170 Added integrated path length s as a reference particle attribute.
  src/initialization/InitDistribution.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/diagnostics/DiagnosticOutput.cpp
  src/particles/elements/ConstF.H
  src/particles/elements/Drift.H
  src/particles/elements/Quad.H
  src/particles/elements/Sbend.H
  src/python/ReferenceParticle.cpp
Labels: component: elements

#174 CUDA: Fix Push (Invalid Lattice Element Members)
  src/particles/Push.cpp
Labels: bug, backend: cuda, bug: affects latest release, workaround

#175 Evolve: More Profiling
  src/initialization/InitMeshRefinement.cpp
  src/particles/ImpactXParticleContainer.cpp
  src/particles/Push.cpp
  src/particles/diagnostics/DiagnosticOutput.cpp
  src/particles/elements/ConstF.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/Multipole.H
  src/particles/elements/None.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/Quad.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
  src/particles/transformation/CoordinateTransformation.cpp
Labels: component: core, component: diagnostics

#176 Corrected FODO README doc.
  examples/fodo/README.rst
Labels: component: documentation, component: tests

#179 Fix Test Directories: Unique
  examples/CMakeLists.txt
Labels: bug, component: tests

#181 add_particles: Resize & Redistribute
  examples/fodo/run_fodo.py
  src/ImpactX.H
  src/initialization/InitDistribution.H
  src/initialization/InitDistribution.cpp
  src/python/ImpactX.cpp
  src/python/distribution.cpp
  tests/python/test_impactx.py
Labels: bug, component: python

#182 CI: Python w/ MPI
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  requirements_mpi.txt
Labels: component: tests, component: python

#185 add name to namespace for Config
  src/python/ImpactX.cpp
Labels: bug, component: python

#183 Add a benchmark example using the IOTA linear lattice.
  docs/source/usage/examples.rst
  examples/CMakeLists.txt
  examples/fodo/run_fodo.py
  examples/iota_lattice/README.rst
  examples/iota_lattice/analysis_iotalattice.py
  examples/iota_lattice/input_iotalattice.in
  examples/iota_lattice/run_iotalattice.py
Labels: component: elements, component: tests

#186 FODO Example: Cleaner Python
  examples/fodo/run_fodo.py
Labels: component: tests, component: python

#187 Chicane Benchmark: Fix Axis Label
  examples/chicane/README.rst
  examples/chicane/plot_chicane.py
Labels: bug, component: documentation, component: tests

#180 Added reference particle helper functions.
  examples/fodo/run_fodo.py
  examples/iota_lattice/run_iotalattice.py
  src/initialization/InitDistribution.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/python/ImpactXParticleContainer.cpp
  src/python/ReferenceParticle.cpp
Labels: component: core
