Repository BLAST-ImpactX/impactx, pull requests merged in 2022-02, with the labels that each got.

#53 Added particle output to file; added Waterbag comments
  src/ImpactX.cpp
  src/particles/distribution/Waterbag.H
Labels: component: documentation, component: diagnostics

#52 Fix Docs of MinAndMaxPositions
  src/particles/ImpactXParticleContainer.H
Labels: bug, component: documentation

#55 Created a data structure to contain reference particle information
  src/ImpactX.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
Labels: component: core

#56 Modified Push and PushSingleParticle functions to access reference
  src/ImpactX.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/particles/Push.cpp
  src/particles/elements/Drift.H
  src/particles/elements/Quad.H
  src/particles/elements/Sbend.H
Labels: component: elements

#59 Elements: Restrict Pointers & References
  src/particles/Push.cpp
  src/particles/elements/Drift.H
  src/particles/elements/Quad.H
  src/particles/elements/Sbend.H
Labels: component: elements, Performance optimization

#57 Doc: Pre-Defined Particle AoS Reals
  src/particles/ImpactXParticleContainer.H
Labels: component: documentation

#60 Add: Particle Shape
  docs/source/usage/parameters.rst
  examples/input_fodo.in
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
Labels: component: core, component: space charge

#61 Update: ABLASTR
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  docs/source/conf.py
Labels: component: third party

#64 Update: ABLASTR
  cmake/dependencies/ABLASTR.cmake
Labels: component: third party

#62 Added function in subfolder "diagnostics" for printing particle data.
  src/ImpactX.cpp
  src/particles/CMakeLists.txt
  src/particles/Push.cpp
  src/particles/diagnostics/CMakeLists.txt
  src/particles/diagnostics/DiagnosticOutput.H
  src/particles/diagnostics/DiagnosticOutput.cpp
Labels: component: diagnostics

#65 Move Diags Between Runs
  src/ImpactX.cpp
  src/particles/diagnostics/DiagnosticOutput.cpp
Labels: component: diagnostics

#30 Charge Deposition
  .github/workflows/ubuntu.yml
  src/ImpactX.H
  src/ImpactX.cpp
  src/particles/CMakeLists.txt
  src/particles/ChargeDeposition.cpp
  src/particles/ImpactXParticleContainer.H
Labels: component: space charge

#67 AddNParticles: Fix SoA assignment for Momentum
  src/particles/ImpactXParticleContainer.cpp
Labels: bug, bug: affects latest release

#69 CI: HIP
  .github/workflows/dependencies/hip.sh
  .github/workflows/hip.yml
  src/ImpactX.cpp
Labels: backend: hip

#70 Moved reference particle access inside "CoordinateTransformation".
  src/ImpactX.cpp
  src/particles/transformation/CoordinateTransformation.H
  src/particles/transformation/CoordinateTransformation.cpp
Labels: component: core
