Repository BLAST-ImpactX/impactx, pull requests merged in 2022-09, with the labels that each got.

#224 Add Python Script for CFChannel
  examples/CMakeLists.txt
  examples/cfchannel/README.rst
  examples/cfchannel/run_cfchannel.py
Labels: component: tests, component: python

#233 Elements: add `ds()` Function
  src/particles/elements/ConstF.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/Multipole.H
  src/particles/elements/None.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/Quad.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
  src/python/elements.cpp
Labels: component: elements, component: python

#236 Perlmutter: Update Batch Script
  etc/impactx/perlmutter-nersc/batch_perlmutter.sh
Labels: component: documentation, machine / system

#237 Add Python input for FODO-RF
  examples/CMakeLists.txt
  examples/fodo_rf/README.rst
  examples/fodo_rf/run_fodo_rf.py
  examples/kurth/README.rst
Labels: changes input scripts / defaults, component: tests, component: python

#214 Add MADX Input Parser
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  examples/chicane/chicane.madx
  examples/chicane/run_chicane_madx.py
  examples/fodo/fodo.madx
  examples/fodo/run_fodo_madx.py
  src/python/elements.cpp
  src/python/impactx/MADXParser.py
  src/python/impactx/__init__.py
  src/python/impactx/madx_to_impactx.py
Labels: changes input scripts / defaults, component: elements, component: python

#238 ABLASTR: 22.09
  cmake/dependencies/ABLASTR.cmake
Labels: component: third party

#228 Ubuntu CI: Split Test & Post-Install Test
  .github/workflows/dependencies/gcc.sh
  .github/workflows/ubuntu.yml
Labels: component: tests

#243 Change tasks-per-node to tasks-per-gpu
  README.md
  docs/source/install/hpc/perlmutter.rst
  etc/impactx/perlmutter-nersc/batch_perlmutter.sh
Labels: component: documentation, machine / system

#242 Modified and renamed coordinate transformations (to fixed t, to fixed s).
  src/ImpactX.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/transformation/CoordinateTransformation.H
  src/particles/transformation/CoordinateTransformation.cpp
  src/particles/transformation/ToFixedS.H
  src/particles/transformation/ToFixedT.H
Labels: component: documentation, component: space charge

#246 ABLASTR: Update
  cmake/dependencies/ABLASTR.cmake
Labels: bug, backend: cuda, component: third party

#172 Python: Test Catch User Errors
  src/ImpactX.H
  src/ImpactX.cpp
  src/initialization/CMakeLists.txt
  src/initialization/InitDistribution.cpp
  src/initialization/InitMeshRefinement.cpp
  src/initialization/Validate.cpp
  src/particles/ImpactXParticleContainer.cpp
  src/particles/transformation/ToFixedS.H
  src/particles/transformation/ToFixedT.H
  src/python/ImpactX.cpp
  tests/python/conftest.py
  tests/python/test_impactx.py
Labels: component: tests, component: python

#240 Expose Control over Domain Resolution & MR Gridding
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  src/ImpactX.cpp
  src/initialization/AmrCoreData.H
  src/initialization/AmrCoreData.cpp
  src/initialization/CMakeLists.txt
  src/initialization/InitAmrCore.H
  src/initialization/InitAmrCore.cpp
  src/initialization/InitMeshRefinement.cpp
  src/initialization/InitOneBoxPerRank.H
  src/initialization/InitOneBoxPerRank.cpp
  src/python/ImpactX.cpp
  tests/python/test_charge_deposition.py
  tests/python/test_impactx.py
Labels: enhancement

#249 Examples: Fix Absolute Tolerance in Analysis (Part 1)
  examples/chicane/analysis_chicane.py
  examples/distgen/analysis_gaussian.py
  examples/distgen/analysis_kurth4d.py
  examples/distgen/analysis_semigaussian.py
  examples/fodo/analysis_fodo.py
  examples/fodo_rf/analysis_fodo_rf.py
  examples/multipole/analysis_multipole.py
Labels: bug, bug: affects latest release, component: tests

#247 geometry.prob_relative: 0.1 -> 1.0
  docs/source/usage/parameters.rst
  src/initialization/InitMeshRefinement.cpp
Labels: changes input scripts / defaults, component: space charge

#251 Charge Deposition: Fix Sign
  src/particles/ChargeDeposition.cpp
  tests/python/test_charge_deposition.py
Labels: bug, bug: affects latest release, component: space charge

#244 Added cold expanding beam benchmark example (with space charge).
  docs/source/usage/examples.rst
  examples/CMakeLists.txt
  examples/expanding_beam/README.rst
  examples/expanding_beam/analysis_expanding.py
  examples/expanding_beam/input_expanding.in
  examples/expanding_beam/run_expanding.py
Labels: component: space charge, component: tests

#252 Replace Hard-Coded Constants with ABLASTR
  cmake/dependencies/ABLASTR.cmake
  src/initialization/InitDistribution.cpp
  src/particles/ImpactXParticleContainer.cpp
  src/particles/ReferenceParticle.H
Labels: component: core, component: distributions

#162 Space Charge Solver
  examples/CMakeLists.txt
  src/ImpactX.H
  src/ImpactX.cpp
  src/initialization/InitMeshRefinement.cpp
  src/particles/CMakeLists.txt
  src/particles/spacecharge/CMakeLists.txt
  src/particles/spacecharge/ForceFromSelfFields.H
  src/particles/spacecharge/ForceFromSelfFields.cpp
  src/particles/spacecharge/GatherAndPush.H
  src/particles/spacecharge/GatherAndPush.cpp
  src/particles/spacecharge/PoissonSolve.H
  src/particles/spacecharge/PoissonSolve.cpp
  src/python/ImpactX.cpp
Labels: component: space charge

#258 Fix: Docs for Sigmas of Distributions
  docs/source/usage/parameters.rst
Labels: bug, component: documentation, bug: affects latest release, component: distributions

#259 CI: GPU Python
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
Labels: backend: cuda, backend: hip, component: tests, component: python

#241 Enable OpenMP in particle push and coordinate transformation routines.
  src/initialization/InitParser.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/particles/Push.cpp
  src/particles/spacecharge/ForceFromSelfFields.cpp
  src/particles/spacecharge/GatherAndPush.cpp
  src/particles/transformation/CoordinateTransformation.cpp
Labels: backend: openmp

#260 Python: All Sim Options As Properties
  docs/source/usage/python.rst
  examples/cfchannel/run_cfchannel.py
  examples/chicane/run_chicane.py
  examples/chicane/run_chicane_madx.py
  examples/expanding_beam/run_expanding.py
  examples/fodo/run_fodo.py
  examples/fodo/run_fodo_madx.py
  examples/fodo_rf/run_fodo_rf.py
  examples/iota_lattice/run_iotalattice.py
  examples/iota_lens/run_iotalens.py
  examples/kurth/run_kurth.py
  examples/multipole/run_multipole.py
  src/python/ImpactX.cpp
  tests/python/test_charge_deposition.py
  tests/python/test_impactx.py
Labels: changes input scripts / defaults, component: python

#263 Examples: Set OMP_NUM_THREADS=2
  examples/CMakeLists.txt
Labels: backend: openmp, component: tests

#264 Diagnostics: Keep File Open
  src/particles/diagnostics/DiagnosticOutput.cpp
Labels: component: diagnostics, Performance optimization

#223 Add Unused Parameter Warnings
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  src/ImpactX.H
  src/ImpactX.cpp
  src/initialization/CMakeLists.txt
  src/initialization/Warnings.cpp
  src/python/ImpactX.cpp
Labels: enhancement

#265 Python: Fix Interactive Inspection
  src/python/ImpactX.cpp
  tests/python/test_impactx.py
Labels: bug, bug: affects latest release, component: python
