Repository BLAST-ImpactX/impactx, pull requests merged in 2023-01, with the labels that each got.

#208 CI: Windows + Python
  .github/workflows/windows.yml
  CMakeLists.txt
  cmake/ImpactXFunctions.cmake
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  setup.py
  src/python/impactx/__init__.py
  tests/python/CMakeLists.txt
Labels: machine / system, component: tests, component: python

#292 Docs: Perlmutter (NERSC) Module Update
  README.md
  docs/source/install/hpc/perlmutter.rst
Labels: component: documentation, backend: cuda, machine / system

#293 Docs: Perlmutter CTest & Python
  README.md
  docs/source/install/hpc/cori.rst
  docs/source/install/hpc/perlmutter.rst
Labels: component: documentation, backend: cuda, machine / system, component: tests

#295 Elements: Mixin Classes
  src/particles/Push.cpp
  src/particles/elements/ConstF.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/Multipole.H
  src/particles/elements/None.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/Quad.H
  src/particles/elements/RFCavity.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
  src/particles/elements/mixin/beamoptic.H
  src/particles/elements/mixin/thick.H
  src/particles/elements/mixin/thin.H
  src/python/elements.cpp
Labels: component: elements

#298 Element: Programmable
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  examples/fodo/run_fodo_programmable.py
  src/particles/CMakeLists.txt
  src/particles/elements/All.H
  src/particles/elements/CMakeLists.txt
  src/particles/elements/Programmable.H
  src/particles/elements/Programmable.cpp
  src/python/ImpactXParticleContainer.cpp
  src/python/elements.cpp
Labels: component: elements, component: python

#300 CI: Cache Action v3
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: component: tests

#303 CI: actions/checkout@v3
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/source.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: component: tests

#302 Add ideal solenoid element
  docs/source/usage/examples.rst
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  examples/solenoid/README.rst
  examples/solenoid/analysis_solenoid.py
  examples/solenoid/input_solenoid.in
  examples/solenoid/run_solenoid.py
  src/initialization/InitElement.cpp
  src/particles/elements/All.H
  src/particles/elements/Sol.H
  src/python/elements.cpp
Labels: component: elements

#308 Docs: Sphinx Needs an "Unused" Import
  docs/source/conf.py
Labels: component: documentation, component: third party
