Repository BLAST-ImpactX/impactx, pull requests merged in 2023-12, with the labels that each got.

#476 Python: `sim.set_diag_iota_invariants()`
  docs/source/usage/python.rst
  examples/iota_lens/run_iotalens.py
  src/particles/diagnostics/NonlinearLensInvariants.H
  src/python/ImpactX.cpp
Labels: component: diagnostics, component: python

#477 Update: ABLASTR, AMReX, pyAMReX
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: third party

#474 Add 6D minimum and maximum values to reduced beam characteristics
  docs/source/dataanalysis/dataanalysis.rst
  src/particles/diagnostics/DiagnosticOutput.cpp
  src/particles/diagnostics/ReducedBeamCharacteristics.cpp
Labels: component: documentation, component: diagnostics

#467 Added an s-dependent IOTA lens example
  examples/CMakeLists.txt
  examples/iota_lattice/README.rst
  examples/iota_lattice/analysis_iotalattice_sdep.py
  examples/iota_lattice/input_iotalattice_sdep.in
  examples/iota_lattice/run_iotalattice_sdep.py
  examples/iota_lens/README.rst
  examples/iota_lens/analysis_iotalens_sdep.py
  examples/iota_lens/input_iotalens_sdep.in
  examples/iota_lens/run_iotalens_sdep.py
  src/particles/diagnostics/NonlinearLensInvariants.H
Labels: component: tests

#479 CI: Remove Brew Cache
  .github/workflows/macos.yml
Labels: component: tests

#480 CI: Pipx for openPMD-validator
  .github/workflows/macos.yml
Labels: component: tests

#478 Release 23.12
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  cmake/dependencies/pybind11.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation, component: third party

#481 CMake: Installed `libimpactx` symlink name
  CMakeLists.txt
Labels: install

#485 CI: Fix ROCm 6.0 `hiprand`
  .github/workflows/dependencies/hip-openmpi.sh
Labels: backend: hip, component: tests

#261 Mesh Refinement
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  examples/cfchannel/run_cfchannel_10nC.py
  examples/expanding_beam/README.rst
  examples/expanding_beam/input_expanding.in
  examples/expanding_beam/run_expanding.py
  src/ImpactX.H
  src/ImpactX.cpp
  src/initialization/InitAmrCore.cpp
  src/initialization/InitMeshRefinement.cpp
  src/particles/ChargeDeposition.cpp
  src/particles/spacecharge/PoissonSolve.H
  src/particles/spacecharge/PoissonSolve.cpp
  src/python/ImpactX.cpp
Labels: component: space charge

#488 Doc: Production/Stable
  README.md
  docs/source/index.rst
  setup.py
Labels: component: documentation

#487 Apochromatic focusing example
  docs/source/usage/examples.rst
  examples/CMakeLists.txt
  examples/apochromatic/README.rst
  examples/apochromatic/analysis_apochromatic.py
  examples/apochromatic/input_apochromatic.in
  examples/apochromatic/run_apochromatic.py
Labels: component: tests
