Repository BLAST-ImpactX/impactx, pull requests merged in 2023-08, with the labels that each got.

#411 Doc: Update License Notice
  LICENSE.txt
  README.md
Labels: component: documentation

#413 CMake: Warnings on AppleClang
  cmake/ImpactXFunctions.cmake
Labels: install

#407 CMake: Remove OBJECT Target
  CMakeLists.txt
  cmake/ImpactXFunctions.cmake
  cmake/dependencies/ABLASTR.cmake
  docs/source/install/cmake.rst
  src/CMakeLists.txt
  src/initialization/CMakeLists.txt
  src/particles/CMakeLists.txt
  src/particles/diagnostics/CMakeLists.txt
  src/particles/elements/CMakeLists.txt
  src/particles/elements/diagnostics/CMakeLists.txt
  src/particles/spacecharge/CMakeLists.txt
  src/particles/transformation/CMakeLists.txt
Labels: bug, bug: affects latest release, install

#416 Python: 3.8+
  docs/source/install/dependencies.rst
  setup.py
Labels: component: documentation, install, component: third party, component: python

#419 Add KICKER to accepted MAD-X input
  examples/CMakeLists.txt
  examples/kicker/README.rst
  examples/kicker/kicker.madx
  examples/kicker/run_kicker_madx.py
  src/python/impactx/MADXParser.py
  src/python/impactx/madx_to_impactx.py
Labels: enhancement, changes input scripts / defaults

#420 MAD-X: Add TKICKER, HKICKER and VKICKER to accepted input
  examples/CMakeLists.txt
  examples/kicker/hvkicker.madx
  examples/kicker/kicker.madx
  examples/kicker/run_hvkicker_madx.py
  src/python/impactx/MADXParser.py
  src/python/impactx/madx_to_impactx.py
Labels: enhancement, changes input scripts / defaults

#423 pyImpactX.H: Add Include Guard
  src/python/pyImpactX.H
Labels: bug, bug: affects latest release, component: python

#424 pytest: Temporary Working Directory
  tests/python/conftest.py
  tests/python/test_charge_deposition.py
  tests/python/test_impactx.py
Labels: bug, bug: affects latest release, component: third party, workaround, component: tests

#426 CMake: Verify ImpactX_..._src paths exit
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  cmake/dependencies/pybind11.cmake
Labels: install

#427 Update clang-tidy Rules
  .clang-tidy
  src/ImpactX.cpp
  src/initialization/InitDistribution.cpp
  src/initialization/InitElement.cpp
  src/initialization/InitMeshRefinement.cpp
  src/initialization/Validate.cpp
  src/initialization/Warnings.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/particles/diagnostics/ReducedBeamCharacteristics.cpp
  src/particles/elements/RFCavity.H
  src/particles/elements/SoftQuad.H
  src/particles/elements/SoftSol.H
  src/particles/elements/diagnostics/openPMD.cpp
  src/particles/spacecharge/ForceFromSelfFields.cpp
  src/particles/transformation/CoordinateTransformation.cpp
  src/python/ImpactX.cpp
  src/python/distribution.cpp
  src/python/elements.cpp
Labels: enhancement, component: core, Performance optimization
