Repository BLAST-ImpactX/impactx, pull requests merged in 2023-07, with the labels that each got.

#390 Docs: openPMD Analysis Examples
  docs/source/dataanalysis/dataanalysis.rst
Labels: component: documentation, component: diagnostics

#399 Release 23.07
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  docs/source/conf.py
  setup.py
  src/particles/spacecharge/PoissonSolve.cpp
Labels: component: documentation, component: third party, workaround

#402 Re-initialize geometry object(s) in initGrids
  examples/cfchannel/run_cfchannel_10nC.py
  examples/expanding_beam/run_expanding.py
  examples/kurth/run_kurth_10nC_periodic.py
  src/ImpactX.cpp
  src/initialization/InitAmrCore.cpp
  src/python/ImpactX.cpp
  tests/python/test_charge_deposition.py
  tests/python/test_impactx.py
Labels: component: python

#403 Add units to Theory documentation.
  docs/source/theory/intro.rst
Labels: component: documentation
