Repository BLAST-ImpactX/impactx, pull requests merged in 2023-06, with the labels that each got.

#362 Add positron LPA channel example
  docs/source/usage/examples.rst
  examples/CMakeLists.txt
  examples/positron_channel/README.rst
  examples/positron_channel/analysis_positron.py
  examples/positron_channel/input_positron.in
  examples/positron_channel/run_positron.py
Labels: component: tests

#373 LPA Channel: Move Periods
  examples/positron_channel/run_positron.py
Labels: component: tests

#375 Release 23.06
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation, component: third party

#382 Doc: Update Desktop Pkg Managers
  docs/source/install/cmake.rst
  docs/source/install/dependencies.rst
Labels: component: documentation, backend: openmp, machine / system, install

#380 openPMD: add software name version
  src/particles/elements/diagnostics/openPMD.cpp
Labels: component: diagnostics

#360 add pythonization of transformation
  .editorconfig
  .gitignore
  docs/source/conf.py
  docs/source/usage/examples.rst
  docs/source/usage/python.rst
  docs/source/usage/tests
  src/python/CMakeLists.txt
  src/python/pyImpactX.cpp
  src/python/transformation.cpp
  tests/python/test_transformation.py
  tests/python/transformation.rst
Labels: component: python

#376 Add exact bend capability for cyclotron
  docs/source/usage/examples.rst
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  examples/cyclotron/analysis_cyclotron.py
  examples/cyclotron/input_cyclotron.in
  examples/cyclotron/run_cyclotron.py
  src/initialization/InitElement.cpp
  src/particles/elements/All.H
  src/particles/elements/ExactSbend.H
  src/python/elements.cpp
Labels: component: tests

#386 CI: Fix macOS Brew CMake
  .github/workflows/macos.yml
Labels: machine / system, install, component: third party, component: tests

#384 Doc: IPAC23 Paper
  docs/source/acknowledge_us.rst
Labels: component: documentation

#387 Add combined function bend element.
  docs/source/usage/examples.rst
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  examples/cfbend/README.rst
  examples/cfbend/analysis_cfbend.py
  examples/cfbend/input_cfbend.in
  examples/cfbend/run_cfbend.py
  examples/cfbend/run_cfbend_madx.py
  src/initialization/InitElement.cpp
  src/particles/elements/All.H
  src/particles/elements/CFbend.H
  src/python/elements.cpp
Labels: component: elements
