Repository BLAST-ImpactX/impactx, pull requests merged in 2023-04, with the labels that each got.

#332 Doc: Update Funding
  README.md
  docs/source/acknowledgements.rst
Labels: component: documentation

#330 Beam Monitor: Output Name
  docs/source/usage/parameters.rst
  src/initialization/InitElement.cpp
Labels: changes input scripts / defaults, component: diagnostics

#329 Monitor in py Examples: Backend Keyword
  examples/cfchannel/run_cfchannel.py
  examples/cfchannel/run_cfchannel_10nC.py
  examples/chicane/run_chicane.py
  examples/expanding_beam/run_expanding.py
  examples/fodo/run_fodo.py
  examples/fodo/run_fodo_programmable.py
  examples/fodo_rf/run_fodo_rf.py
  examples/iota_lattice/run_iotalattice.py
  examples/kurth/run_kurth_10nC_periodic.py
  examples/kurth/run_kurth_periodic.py
  examples/multipole/run_multipole.py
  examples/quadrupole_softedge/run_quadrupole_softedge.py
  examples/rfcavity/run_rfcavity.py
  examples/solenoid/run_solenoid.py
  examples/solenoid_softedge/run_solenoid_softedge.py
  src/python/impactx/madx_to_impactx.py
Labels: component: documentation, changes input scripts / defaults, component: diagnostics, component: elements, component: tests

#315 Release 23.04
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  docs/source/conf.py
  docs/source/install/dependencies.rst
  setup.py
Labels: component: documentation, component: third party

#317 Add Pole-Face Rotation Element (prot)
  docs/source/usage/examples.rst
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  examples/rotation/README.rst
  examples/rotation/analysis_rotation.py
  examples/rotation/input_rotation.in
  examples/rotation/run_rotation.py
  src/initialization/InitElement.cpp
  src/particles/elements/All.H
  src/particles/elements/PRot.H
  src/python/elements.cpp
Labels: component: elements

#339 amrex.the_arena_is_managed=0
  docs/source/usage/parameters.rst
  src/ImpactX.cpp
  src/initialization/InitParser.cpp
  src/particles/PushAll.H
  src/particles/elements/ConstF.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/Multipole.H
  src/particles/elements/None.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/PRot.H
  src/particles/elements/Programmable.H
  src/particles/elements/Programmable.cpp
  src/particles/elements/Quad.H
  src/particles/elements/RFCavity.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
  src/particles/elements/SoftQuad.H
  src/particles/elements/SoftSol.H
  src/particles/elements/Sol.H
  src/particles/elements/mixin/nofinalize.H
  tests/python/conftest.py
  tests/python/test_charge_deposition.py
Labels: backend: cuda, backend: dpc++, backend: hip, changes input scripts / defaults, Performance optimization

#335 New Element: Line
  docs/source/usage/parameters.rst
  examples/iota_lattice/input_iotalattice.in
  src/initialization/InitElement.cpp
Labels: component: elements

#340 Python Tests: w/o Managed Memory
  cmake/dependencies/pyAMReX.cmake
  tests/python/conftest.py
  tests/python/test_charge_deposition.py
Labels: backend: cuda, backend: dpc++, backend: hip, Performance optimization, component: tests, component: python

#342 AMReX: Update to New Particle APIs
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  src/particles/ImpactXParticleContainer.cpp
Labels: component: third party

#341 expose creation of iterators to python
  src/python/ImpactXParticleContainer.cpp
Labels: component: python

#343 CI: macOS
  .github/workflows/macos.yml
Labels: component: tests

#346 Doc: Theory Ref. Trajectory
  docs/source/theory/intro.rst
Labels: component: documentation

#347 CI: macOS Install
  .github/workflows/macos.yml
Labels: component: tests

#349 Fix openPMD Meta-Data
  .github/workflows/dependencies/gcc-openmpi.sh
  .github/workflows/dependencies/gcc.sh
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  src/particles/elements/diagnostics/openPMD.H
  src/particles/elements/diagnostics/openPMD.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#351 Particle Enums: Use Consistently and Rename
  docs/source/usage/python.rst
  examples/cfchannel/analysis_cfchannel.py
  examples/cfchannel/analysis_cfchannel_10nC.py
  examples/chicane/analysis_chicane.py
  examples/chicane/plot_chicane.py
  examples/distgen/analysis_gaussian.py
  examples/distgen/analysis_kurth4d.py
  examples/distgen/analysis_kvdist.py
  examples/distgen/analysis_semigaussian.py
  examples/expanding_beam/analysis_expanding.py
  examples/fodo/analysis_fodo.py
  examples/fodo/plot_fodo.py
  examples/fodo_rf/analysis_fodo_rf.py
  examples/iota_lattice/analysis_iotalattice.py
  examples/kurth/analysis_kurth.py
  examples/kurth/analysis_kurth_10nC.py
  examples/kurth/analysis_kurth_10nC_periodic.py
  examples/kurth/analysis_kurth_periodic.py
  examples/multipole/analysis_multipole.py
  examples/quadrupole_softedge/analysis_quadrupole_softedge.py
  examples/rfcavity/analysis_rfcavity.py
  examples/rotation/analysis_rotation.py
  examples/solenoid/analysis_solenoid.py
  examples/solenoid_softedge/analysis_solenoid_softedge.py
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/particles/ReferenceParticle.H
  src/particles/diagnostics/DiagnosticOutput.cpp
  src/particles/elements/ConstF.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/Multipole.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/PRot.H
  src/particles/elements/Quad.H
  src/particles/elements/RFCavity.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
  src/particles/elements/SoftQuad.H
  src/particles/elements/SoftSol.H
  src/particles/elements/Sol.H
  src/particles/elements/diagnostics/openPMD.cpp
  src/particles/spacecharge/GatherAndPush.cpp
  src/particles/transformation/CoordinateTransformation.cpp
  src/particles/transformation/ToFixedS.H
  src/particles/transformation/ToFixedT.H
  src/python/ImpactXParticleContainer.cpp
Labels: component: core
