Repository BLAST-ImpactX/impactx, pull requests merged in 2024-04, with the labels that each got.

#571 Named SoA: Check and Index Getter
  src/ImpactX.cpp
  src/particles/CollectLost.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
Labels: component: core

#566 Docs: Add Example Subsections
  docs/source/usage/examples.rst
Labels: component: documentation

#565 Diagnostics: NLL Invariants to Monitor
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  examples/iota_lattice/analysis_iotalattice_sdep.py
  examples/iota_lattice/input_iotalattice.in
  examples/iota_lattice/input_iotalattice_sdep.in
  examples/iota_lattice/run_iotalattice_sdep.py
  examples/iota_lens/analysis_iotalens.py
  examples/iota_lens/analysis_iotalens_sdep.py
  examples/iota_lens/input_iotalens.in
  examples/iota_lens/input_iotalens_sdep.in
  examples/iota_lens/run_iotalens.py
  examples/iota_lens/run_iotalens_sdep.py
  src/ImpactX.cpp
  src/initialization/InitElement.cpp
  src/particles/diagnostics/DiagnosticOutput.cpp
  src/particles/diagnostics/NonlinearLensInvariants.H
  src/particles/elements/diagnostics/AdditionalProperties.cpp
  src/particles/elements/diagnostics/CMakeLists.txt
  src/particles/elements/diagnostics/openPMD.H
  src/particles/elements/diagnostics/openPMD.cpp
  src/python/ImpactX.cpp
  src/python/elements.cpp
Labels: component: diagnostics, Performance optimization

#560 Feature: Initialize beam from arrays
  docs/source/usage/examples.rst
  examples/CMakeLists.txt
  examples/initialize_from_array/README.rst
  examples/initialize_from_array/analyze_from_array.py
  examples/initialize_from_array/impactx_read_utilities.py
  examples/initialize_from_array/run_from_array.py
  examples/initialize_from_array/transformation_utilities.py
  examples/initialize_from_array/visualize_from_array.py
Labels: component: documentation, enhancement, component: tests, component: distributions, component: python

#469 MPL: `ImpactXParticleContainer.plot_phasespace()`
  .github/workflows/dependencies/gcc.sh
  README.md
  docs/source/dataanalysis/dataanalysis.rst
  docs/source/install/dependencies.rst
  examples/requirements.txt
  requirements.txt
  src/python/impactx/ImpactXParticleContainer.py
  src/python/impactx/__init__.py
  tests/python/test_dataframe.py
Labels: component: python

#573 Doc: Beam Distributions
  docs/source/usage/examples.rst
Labels: component: documentation

#577 Fix Python Init Order
  cmake/dependencies/pyAMReX.cmake
  src/python/ImpactXParticleContainer.cpp
  src/python/elements.cpp
  src/python/pyImpactX.cpp
Labels: bug, bug: affects latest release, component: python

#587 Fix macOS CI: DYLD Lib Path
  .github/workflows/macos.yml
Labels: bug, machine / system, component: third party, component: tests

#576 openPMD-api: 0.15.2
  cmake/dependencies/ABLASTR.cmake
  docs/source/install/dependencies.rst
Labels: component: third party, component: diagnostics

#591 Test: Relax Tolerance (OMP)
  examples/initialize_from_array/analyze_from_array.py
Labels: backend: openmp, component: tests

#590 Correction to Zeuthen chicane input
  examples/chicane/chicane.madx
  examples/chicane/input_chicane.in
  examples/chicane/run_chicane.py
Labels: component: tests

#589 Doc: HB2023 Papers
  docs/source/acknowledge_us.rst
Labels: component: documentation

#578 CI: Python Stubs
  .github/update_stub.sh
  .github/workflows/stubs.yml
  docs/requirements.txt
  docs/spack.yaml
Labels: component: documentation, component: tests, component: python

#593 Fix: `None` -> `Empty` Element/Dist
  docs/source/usage/python.rst
  examples/aperture/run_aperture.py
  examples/fodo_tune/run_fodo_tune.py
  examples/initialize_from_array/run_from_array.py
  examples/optimize_triplet/run_triplet.py
  examples/pytorch_surrogate_model/run_ml_surrogate_15_stage.py
  src/particles/distribution/All.H
  src/particles/distribution/Empty.H
  src/particles/elements/All.H
  src/particles/elements/Empty.H
  src/python/distribution.cpp
  src/python/elements.cpp
  src/python/impactx/__init__.pyi
  src/python/impactx/impactx_pybind/__init__.pyi
  src/python/impactx/impactx_pybind/distribution.pyi
  src/python/impactx/impactx_pybind/elements.pyi
  tests/python/conftest.py
  tests/python/test_charge_deposition.py
  tests/python/test_dataframe.py
  tests/python/test_impactx.py
  tests/python/test_transformation.py
  tests/python/test_xopt.py
Labels: bug, bug: affects latest release, changes input scripts / defaults, component: elements, component: distributions, component: python
