Repository BLAST-ImpactX/impactx, pull requests merged in 2024-02, with the labels that each got.

#513 Add ImpactX_CCACHE Option
  CMakeLists.txt
  docs/source/install/cmake.rst
Labels: install

#514 Add chromatic plasma lens model
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  examples/apochromatic/README.rst
  examples/apochromatic/analysis_apochromatic_pl.py
  examples/apochromatic/input_apochromatic_pl.in
  examples/apochromatic/run_apochromatic_pl.py
  src/initialization/InitElement.cpp
  src/particles/elements/All.H
  src/particles/elements/ChrPlasmaLens.H
  src/python/elements.cpp
Labels: component: elements, component: tests

#517 CI: Fix Tooling `-Wno-error=pass-failed`
  .github/workflows/tooling.yml
Labels: component: tests, warning

#518 Programmable Element: Profile `pc` Push
  src/particles/elements/Programmable.cpp
Labels: component: python

#519 Python Examples: Finalize Sim
  examples/alignment/run_alignment.py
  examples/aperture/run_aperture.py
  examples/apochromatic/run_apochromatic.py
  examples/apochromatic/run_apochromatic_pl.py
  examples/cfbend/run_cfbend.py
  examples/cfbend/run_cfbend_madx.py
  examples/cfchannel/run_cfchannel.py
  examples/cfchannel/run_cfchannel_10nC.py
  examples/chicane/run_chicane.py
  examples/chicane/run_chicane_madx.py
  examples/compression/run_compression.py
  examples/cyclotron/run_cyclotron.py
  examples/epac2004_benchmarks/run_bithermal.py
  examples/epac2004_benchmarks/run_fodo_rf_SC.py
  examples/epac2004_benchmarks/run_thermal.py
  examples/expanding_beam/run_expanding.py
  examples/fodo/run_fodo.py
  examples/fodo/run_fodo_madx.py
  examples/fodo/run_fodo_programmable.py
  examples/fodo_chromatic/run_fodo_chr.py
  examples/fodo_rf/run_fodo_rf.py
  examples/iota_lattice/run_iotalattice.py
  examples/iota_lattice/run_iotalattice_sdep.py
  examples/iota_lens/run_iotalens.py
  examples/iota_lens/run_iotalens_sdep.py
  examples/kicker/run_hvkicker_madx.py
  examples/kicker/run_kicker.py
  examples/kicker/run_kicker_madx.py
  examples/kurth/run_kurth_10nC_periodic.py
  examples/kurth/run_kurth_periodic.py
  examples/multipole/run_multipole.py
  examples/positron_channel/run_positron.py
  examples/pytorch_surrogate_model/run_ml_surrogate.py
  examples/quadrupole_softedge/run_quadrupole_softedge.py
  examples/rfcavity/run_rfcavity.py
  examples/rotation/run_rotation.py
  examples/solenoid/run_solenoid.py
  examples/solenoid/run_solenoid_madx.py
  examples/solenoid_softedge/run_solenoid_softedge.py
  examples/thin_dipole/run_thin_dipole.py
Labels: bug, component: tests, component: python

#520 Tests: Mark `thermal` as slow
  .github/workflows/tooling.yml
  .github/workflows/ubuntu.yml
  examples/CMakeLists.txt
Labels: component: tests

#515 Release 24.02
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation, component: third party

#522 CI: Add `ruff`
  .pre-commit-config.yaml
  examples/alignment/run_alignment.py
  examples/aperture/run_aperture.py
  examples/apochromatic/run_apochromatic.py
  examples/apochromatic/run_apochromatic_pl.py
  examples/cfbend/run_cfbend.py
  examples/cfbend/run_cfbend_madx.py
  examples/cfchannel/run_cfchannel.py
  examples/cfchannel/run_cfchannel_10nC.py
  examples/chicane/run_chicane.py
  examples/chicane/run_chicane_madx.py
  examples/compression/run_compression.py
  examples/cyclotron/run_cyclotron.py
  examples/epac2004_benchmarks/run_bithermal.py
  examples/epac2004_benchmarks/run_fodo_rf_SC.py
  examples/epac2004_benchmarks/run_thermal.py
  examples/expanding_beam/run_expanding.py
  examples/fodo/run_fodo.py
  examples/fodo/run_fodo_madx.py
  examples/fodo/run_fodo_programmable.py
  examples/fodo_chromatic/run_fodo_chr.py
  examples/fodo_rf/run_fodo_rf.py
  examples/iota_lattice/run_iotalattice.py
  examples/iota_lattice/run_iotalattice_sdep.py
  examples/iota_lens/run_iotalens.py
  examples/iota_lens/run_iotalens_sdep.py
  examples/kicker/run_hvkicker_madx.py
  examples/kicker/run_kicker.py
  examples/kicker/run_kicker_madx.py
  examples/kurth/run_kurth_10nC_periodic.py
  examples/kurth/run_kurth_periodic.py
  examples/multipole/run_multipole.py
  examples/positron_channel/run_positron.py
  examples/pytorch_surrogate_model/run_ml_surrogate.py
  examples/pytorch_surrogate_model/surrogate_model_definitions.py
  examples/pytorch_surrogate_model/visualize_ml_surrogate.py
  examples/quadrupole_softedge/run_quadrupole_softedge.py
  examples/rfcavity/run_rfcavity.py
  examples/rotation/run_rotation.py
  examples/solenoid/run_solenoid.py
  examples/solenoid/run_solenoid_madx.py
  examples/solenoid_softedge/run_solenoid_softedge.py
  examples/thin_dipole/run_thin_dipole.py
  pyproject.toml
  src/python/impactx/MADXParser.py
  tests/python/conftest.py
  tests/python/test_impactx.py
  tests/python/test_transformation.py
Labels: component: tests, component: python

#521 Implement `int` SoA Names
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/python/ImpactXParticleContainer.cpp
Labels: component: core

#524 Simplify Finalize
  src/ImpactX.cpp
Labels: bug

#348 Update Particle Container to Pure SoA
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  examples/epac2004_benchmarks/input_fodo_rf_SC.in
  examples/fodo/run_fodo_programmable.py
  examples/pytorch_surrogate_model/run_ml_surrogate.py
  examples/pytorch_surrogate_model/surrogate_model_definitions.py
  src/particles/CollectLost.cpp
  src/particles/ImpactXParticleContainer.H
  src/particles/ImpactXParticleContainer.cpp
  src/particles/diagnostics/DiagnosticOutput.cpp
  src/particles/diagnostics/ReducedBeamCharacteristics.cpp
  src/particles/elements/Aperture.H
  src/particles/elements/Buncher.H
  src/particles/elements/CFbend.H
  src/particles/elements/ChrDrift.H
  src/particles/elements/ChrPlasmaLens.H
  src/particles/elements/ChrQuad.H
  src/particles/elements/ChrUniformAcc.H
  src/particles/elements/ConstF.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/ExactDrift.H
  src/particles/elements/ExactSbend.H
  src/particles/elements/Kicker.H
  src/particles/elements/Multipole.H
  src/particles/elements/None.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/PRot.H
  src/particles/elements/Quad.H
  src/particles/elements/RFCavity.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
  src/particles/elements/SoftQuad.H
  src/particles/elements/SoftSol.H
  src/particles/elements/Sol.H
  src/particles/elements/ThinDipole.H
  src/particles/elements/diagnostics/openPMD.cpp
  src/particles/elements/mixin/beamoptic.H
  src/particles/integrators/Integrators.H
  src/particles/spacecharge/GatherAndPush.cpp
  src/particles/transformation/CoordinateTransformation.cpp
  src/particles/transformation/ToFixedS.H
  src/particles/transformation/ToFixedT.H
  src/python/ImpactXParticleContainer.cpp
  src/python/Iterator.H
  src/python/impactx/ImpactXParIter.py
  src/python/impactx/ImpactXParticleContainer.py
  src/python/impactx/__init__.py
  tests/python/test_dataframe.py
  tests/python/test_impactx.py
  tests/python/test_push.py
Labels: component: core, Performance optimization

#516 Add example of tune calculation (postprocessing)
  docs/source/usage/examples.rst
  examples/CMakeLists.txt
  examples/fodo_tune/README.rst
  examples/fodo_tune/analysis_fodo_tune.py
  examples/fodo_tune/input_fodo_tune.in
  examples/fodo_tune/run_fodo_tune.py
  examples/requirements.txt
Labels: component: diagnostics

#523 CI: 4 Cores Linux/Win, 3 Cores macOS
  .github/workflows/codeql.yml
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/tooling.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  examples/CMakeLists.txt
  examples/apochromatic/analysis_apochromatic.py
  examples/epac2004_benchmarks/analysis_bithermal.py
  examples/positron_channel/analysis_positron.py
  tests/python/CMakeLists.txt
Labels: component: tests

#530 CI: Run with 2 Cores
  .github/workflows/ubuntu.yml
  examples/CMakeLists.txt
  tests/python/CMakeLists.txt
Labels: component: tests

#531 Use new function from Alex for removing invalid particles.
  cmake/dependencies/ABLASTR.cmake
  src/particles/CollectLost.cpp
Labels: bug, backend: cuda, backend: dpc++, backend: hip, bug: affects latest release

#527 Add initialization from Twiss parameters
  docs/source/theory/intro.rst
  docs/source/theory/phase_space_ellipse.svg
  docs/source/usage/parameters.rst
  examples/CMakeLists.txt
  examples/distgen/input_kvdist_twiss.in
  examples/fodo/input_fodo_twiss.in
  src/initialization/InitDistribution.H
  src/initialization/InitDistribution.cpp
Labels: component: distributions
