Repository BLAST-ImpactX/impactx, pull requests merged in 2024-08, with the labels that each got.

#655 CMake: Simplify Python `add_impactx_test`
  examples/CMakeLists.txt
Labels: install, component: tests

#659 CMake: Fix ABLASTR FFTW Superbuild
  cmake/dependencies/ABLASTR.cmake
Labels: bug, install

#660 Update: ABLASTR, pyAMReX
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  src/initialization/InitAmrCore.cpp
  src/particles/spacecharge/PoissonSolve.cpp
Labels: component: third party

#651 Trame Dashboard
  .gitignore
  docs/source/index.rst
  docs/source/install/dependencies.rst
  docs/source/usage/dashboard.rst
  setup.py
  src/python/impactx/dashboard/Analyze/__init__.py
  src/python/impactx/dashboard/Analyze/analyzeFunctions.py
  src/python/impactx/dashboard/Analyze/plot_ParameterEvolutionOverS/overS.py
  src/python/impactx/dashboard/Analyze/plot_PhaseSpaceProjections/phaseSpace.py
  src/python/impactx/dashboard/Analyze/plot_PhaseSpaceProjections/phaseSpaceSettings.py
  src/python/impactx/dashboard/Analyze/plotsMain.py
  src/python/impactx/dashboard/Input/__init__.py
  src/python/impactx/dashboard/Input/distributionParameters/__init__.py
  src/python/impactx/dashboard/Input/distributionParameters/distributionMain.py
  src/python/impactx/dashboard/Input/generalFunctions.py
  src/python/impactx/dashboard/Input/inputParameters/__init__.py
  src/python/impactx/dashboard/Input/inputParameters/inputFunctions.py
  src/python/impactx/dashboard/Input/inputParameters/inputMain.py
  src/python/impactx/dashboard/Input/latticeConfiguration/__init__.py
  src/python/impactx/dashboard/Input/latticeConfiguration/latticeMain.py
  src/python/impactx/dashboard/Input/trameFunctions.py
  src/python/impactx/dashboard/Toolbar/__init__.py
  src/python/impactx/dashboard/Toolbar/toolbarMain.py
  src/python/impactx/dashboard/__init__.py
  src/python/impactx/dashboard/__main__.py
  src/python/impactx/dashboard/jupyterApplication.py
  src/python/impactx/dashboard/requirements.txt
  src/python/impactx/dashboard/start.py
  src/python/impactx/dashboard/trame_setup.py
Labels: component: dashboard

#671 CI: Ruff replaced Tools
  .pre-commit-config.yaml
Labels: component: tests

#657 Release 24.08
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#673 CMake: More Pip Control Options
  CMakeLists.txt
  docs/source/install/cmake.rst
Labels: install, component: python

#674 CI: Python Requirements Update
  .github/workflows/dependencies/clang-san-openmpi.sh
  .github/workflows/dependencies/clang-tidy.sh
  .github/workflows/dependencies/gcc-openmpi.sh
  .github/workflows/dependencies/gcc.sh
  .github/workflows/macos.yml
  .github/workflows/stubs.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: component: tests

#679 Ruff: Run on pyi files
  .pre-commit-config.yaml
  src/python/impactx/MADXParser.pyi
  src/python/impactx/__init__.pyi
  src/python/impactx/extensions/__init__.pyi
  src/python/impactx/impactx_pybind/__init__.pyi
  src/python/impactx/impactx_pybind/elements.pyi
  src/python/impactx/madx_to_impactx.pyi
Labels: component: tests

#676 `setup.py`: More Unique `build_base`
  setup.py
Labels: bug, bug: affects latest release, install, component: python

#681 Modify qm_qeeV name and docs.
  docs/source/usage/python.rst
  src/initialization/InitDistribution.cpp
  src/particles/ReferenceParticle.H
  src/python/ReferenceParticle.cpp
  src/python/impactx/impactx_pybind/__init__.pyi
Labels: bug, bug: affects latest release, component: core

#683 Update ABLASTR & pyAMReX
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: third party

#684 Doc: Reorganize Sections for Collective Effects
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
Labels: component: documentation, component: space charge, component: CSR

#682 Add dispersion to reduced diagnostics
  docs/source/usage/examples.rst
  examples/CMakeLists.txt
  examples/dogleg/README.rst
  examples/dogleg/analysis_dogleg.py
  examples/dogleg/dogleg.madx
  examples/dogleg/input_dogleg.in
  examples/dogleg/optics_madx
  examples/dogleg/run_dogleg.py
  src/particles/diagnostics/DiagnosticOutput.cpp
  src/particles/diagnostics/ReducedBeamCharacteristics.cpp
Labels: component: diagnostics

#686 Add documentation for reduced diagnostics: dispersion output.
  docs/source/dataanalysis/dataanalysis.rst
Labels: component: documentation, component: diagnostics

#627 1D CSR Model
  .github/workflows/windows.yml
  docs/source/usage/examples.rst
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  examples/chicane/README.rst
  examples/chicane/README_csr.rst
  examples/chicane/analysis_chicane_csr.py
  examples/chicane/input_chicane_csr.in
  examples/chicane/run_chicane_csr.py
  src/ImpactX.cpp
  src/particles/CMakeLists.txt
  src/particles/ImpactXParticleContainer.H
  src/particles/elements/ExactSbend.H
  src/particles/wakefields/CMakeLists.txt
  src/particles/wakefields/CSRBendElement.H
  src/particles/wakefields/ChargeBinning.H
  src/particles/wakefields/ChargeBinning.cpp
  src/particles/wakefields/HandleWakefield.H
  src/particles/wakefields/WakeConvolution.H
  src/particles/wakefields/WakeConvolution.cpp
  src/particles/wakefields/WakePush.H
  src/particles/wakefields/WakePush.cpp
  src/python/CMakeLists.txt
  src/python/ImpactX.cpp
  src/python/WakeConvolution.cpp
  src/python/pyImpactX.cpp
  tests/python/test_charge_deposition.py
Labels: component: CSR

#691 Update Dashboard Info Verbiage
  docs/source/usage/dashboard.rst
  src/python/impactx/dashboard/Toolbar/toolbarMain.py
  src/python/impactx/dashboard/__main__.py
Labels: component: documentation, component: dashboard

#689 CMake: Replace `FetchContent_Populate`
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  cmake/dependencies/pybind11.cmake
  docs/source/install/dependencies.rst
  pyproject.toml
  setup.py
Labels: install, warning
