Repository BLAST-ImpactX/impactx, pull requests merged in 2024-06, with the labels that each got.

#628 Fix: LUMI-C OpenMP Python
  docs/source/install/hpc/lumi-csc/install_cpu_dependencies.sh
  docs/source/install/hpc/lumi-csc/lumi_cpu_impactx.profile.example
Labels: bug, component: documentation, machine / system

#633 CI: Work-Around GH Action Runner Win
  .github/workflows/windows.yml
Labels: bug, machine / system, component: third party, workaround, component: tests

#635 Doc: Corrected typo in the section of RFCavity
  docs/source/usage/python.rst
Labels: bug, component: documentation, bug: affects latest release

#624 Doc: Add Custom Elements
  docs/source/install/hpc/perlmutter.rst
  docs/source/usage/how_to_run.rst
  docs/source/usage/python.rst
  docs/source/usage/workflows.rst
  docs/source/usage/workflows/add_element.rst
  examples/fodo_programmable/README.rst
Labels: component: documentation

#637 Release 24.06
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  docs/source/conf.py
  setup.py
  src/particles/spacecharge/PoissonSolve.cpp
Labels: component: documentation

#640 CI: CCache for macOS
  .github/workflows/macos.yml
Labels: component: tests
