Repository BLAST-ImpactX/impactx, pull requests merged in 2024-09, with the labels that each got.

#692 Doc: Intro Update
  docs/source/index.rst
Labels: component: documentation

#698 Remove additional string for Twiss input
  docs/source/usage/parameters.rst
  examples/fodo/input_fodo_twiss.in
  src/initialization/InitDistribution.cpp
Labels: changes input scripts / defaults, component: distributions

#697 Add helper function for Python Twiss input
  docs/source/usage/python.rst
  examples/CMakeLists.txt
  examples/distgen/README.rst
  examples/distgen/input_gaussian_twiss.in
  examples/distgen/input_kvdist.in
  examples/distgen/run_gaussian_twiss.py
  examples/distgen/run_kurth4d.py
  examples/distgen/run_kvdist_twiss.py
  examples/distgen/run_semigaussian.py
  examples/fodo/run_fodo_twiss.py
  src/python/impactx/__init__.py
  src/python/impactx/distribution_input_helpers.py
Labels: component: python

#701 Fix literal includes of KV test files in DistGen example
  examples/distgen/README.rst
Labels: bug, component: documentation, bug: affects latest release

#695 Release: 24.09
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#707 Fix special case of pt_ms=0 in dispersive diagnostics.
  src/particles/diagnostics/ReducedBeamCharacteristics.cpp
Labels: bug: affects latest release

#708 LUMI (CSC): September Upgrade
  docs/source/install/hpc/lumi-csc/lumi_cpu_impactx.profile.example
  docs/source/install/hpc/lumi-csc/lumi_gpu_impactx.profile.example
Labels: component: documentation, machine / system

#710 Rename element `name` to `type`
  docs/source/usage/workflows/add_element.rst
  src/particles/PushAll.H
  src/particles/elements/Aperture.H
  src/particles/elements/Buncher.H
  src/particles/elements/CFbend.H
  src/particles/elements/ChrDrift.H
  src/particles/elements/ChrPlasmaLens.H
  src/particles/elements/ChrQuad.H
  src/particles/elements/ChrUniformAcc.H
  src/particles/elements/ConstF.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/Empty.H
  src/particles/elements/ExactDrift.H
  src/particles/elements/ExactSbend.H
  src/particles/elements/Kicker.H
  src/particles/elements/Multipole.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/PRot.H
  src/particles/elements/Programmable.H
  src/particles/elements/Quad.H
  src/particles/elements/RFCavity.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
  src/particles/elements/SoftQuad.H
  src/particles/elements/SoftSol.H
  src/particles/elements/Sol.H
  src/particles/elements/TaperedPL.H
  src/particles/elements/ThinDipole.H
  src/particles/elements/diagnostics/AdditionalProperties.cpp
  src/particles/elements/diagnostics/openPMD.H
  src/particles/elements/diagnostics/openPMD.cpp
Labels: component: elements

#716 `<cmath>`: Use `std::` C++ Functions
  src/particles/ReferenceParticle.H
  src/particles/distribution/Gaussian.H
  src/particles/distribution/KVdist.H
  src/particles/distribution/Kurth4D.H
  src/particles/distribution/Kurth6D.H
  src/particles/distribution/Semigaussian.H
  src/particles/distribution/Thermal.H
  src/particles/distribution/Triangle.H
  src/particles/elements/Aperture.H
  src/particles/elements/Buncher.H
  src/particles/elements/CFbend.H
  src/particles/elements/ChrDrift.H
  src/particles/elements/ChrPlasmaLens.H
  src/particles/elements/ChrQuad.H
  src/particles/elements/ChrUniformAcc.H
  src/particles/elements/ConstF.H
  src/particles/elements/DipEdge.H
  src/particles/elements/Drift.H
  src/particles/elements/ExactDrift.H
  src/particles/elements/ExactSbend.H
  src/particles/elements/Multipole.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/PRot.H
  src/particles/elements/RFCavity.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
  src/particles/elements/SoftQuad.H
  src/particles/elements/SoftSol.H
  src/particles/elements/Sol.H
  src/particles/elements/ThinDipole.H
  src/particles/integrators/Integrators.H
  src/particles/transformation/CoordinateTransformation.cpp
  src/particles/transformation/ToFixedS.H
  src/particles/transformation/ToFixedT.H
Labels: component: core, component: elements, Performance optimization, component: distributions, component: CSR

#715 Update ABLASTR & pyAMReX
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  src/particles/spacecharge/PoissonSolve.cpp
Labels: component: third party
