Repository BLAST-ImpactX/impactx, pull requests merged in 2024-03, with the labels that each got.

#540 Fix: Windows add_dll_directory Expand
  src/python/impactx/__init__.py
Labels: bug, bug: affects latest release, machine / system, component: python

#542 Python: Add `__repr__` for all Elements
  examples/multipole/run_multipole.py
  src/particles/elements/Buncher.H
  src/particles/elements/CFbend.H
  src/particles/elements/DipEdge.H
  src/particles/elements/ExactSbend.H
  src/particles/elements/Kicker.H
  src/particles/elements/Multipole.H
  src/particles/elements/NonlinearLens.H
  src/particles/elements/PRot.H
  src/particles/elements/Quad.H
  src/particles/elements/RFCavity.H
  src/particles/elements/Sbend.H
  src/particles/elements/ShortRF.H
  src/particles/elements/SoftQuad.H
  src/particles/elements/SoftSol.H
  src/particles/elements/Sol.H
  src/particles/elements/ThinDipole.H
  src/python/elements.cpp
Labels: component: python

#543 ImpactX: Verbosity Control
  docs/source/usage/parameters.rst
  docs/source/usage/python.rst
  src/ImpactX.cpp
  src/initialization/Warnings.cpp
  src/python/ImpactX.cpp
Labels: component: core

#535 Zenodo: Add Ji's ORCiD
  .zenodo.json
Labels: component: documentation

#544 `diags/` Folder: Only w/ Diags
  src/ImpactX.cpp
Labels: component: diagnostics

#545 Release: 24.03
  CMakeLists.txt
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation, component: third party

#554 CI: Dependabot
  .github/dependabot.yml
Labels: component: tests

#551 Doc: Conda Update
  docs/source/install/dependencies.rst
  docs/source/install/users.rst
Labels: component: documentation, install, component: third party

#564 Adding documentation for Integrator.H
  src/particles/integrators/Integrators.H
Labels: component: documentation

#541 Add theory documentation for covariance matrix/quadratic form.
  docs/source/theory/intro.rst
Labels: component: documentation

#539 Add quad triplet optimization example
  docs/source/usage/examples.rst
  examples/CMakeLists.txt
  examples/fodo/README.rst
  examples/optimize_triplet/README.rst
  examples/optimize_triplet/analysis_triplet.py
  examples/optimize_triplet/plot_triplet.py
  examples/optimize_triplet/run_triplet.py
  examples/optimize_triplet/test_xopt.py
  tests/python/requirements.txt
  tests/python/test_dataframe.py
  tests/python/test_xopt.py
Labels: component: tests

#561 Clean up ReducedBeamCharacteristics with TypeMultiplier
  src/particles/diagnostics/ReducedBeamCharacteristics.cpp
Labels: component: diagnostics

#568 Update: ABLASTR, pyAMReX
  cmake/dependencies/ABLASTR.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: third party

#570 Doc: LUMI
  docs/source/install/hpc.rst
  docs/source/install/hpc/lumi-csc/install_dependencies.sh
  docs/source/install/hpc/lumi-csc/lumi_impactx.profile.example
  docs/source/install/hpc/lumi-csc/submit.sh
  docs/source/install/hpc/lumi.rst
Labels: component: documentation, machine / system
